### ISSUE TITLE
Why not use LowerLeft and LowerRight?

### ISSUE THREAD

**Issue by MI11435** [WickyPlays/DankaguLike_GLWickyPack#2]
https://github.com/WickyPlays/DankaguLike_GLWickyPack/blob/main/modules%2FDifficulty%2Fcore.lua#L27-L27
https://github.com/WickyPlays/DankaguLike_GLWickyPack/blob/main/modules%2FSongTitle%2Fcore.lua#L27-L27
UpperLeftやUpperRightだと、Sizeの値を大きくすると文字が下にはみ出てしまう。

With UpperLeft and UpperRight, if the Size value is increased, the text will protrude below.
(Translated by DeepL)

**Comment by WickyPlays** [comment]
Normally, you would be right about this.

However, since WickyCanvas has already defined the canvas itself as 1920x1080 [as defined here](https://github.com/WickyPlays/DankaguLike_GLWickyPack/blob/main/tools/utils.lua#L45C1-L46C1), the resolution even when full screen will stick itself as 1920x1080 resolution, therefore changes from UpperLeft to LowerLeft would not change the outcome when I already have the bottom pixel (-1002) [as defined here](https://github.com/WickyPlays/DankaguLike_GLWickyPack/blob/main/modules/Difficulty/core.lua#L63).

I guess it's a good safety technique, at least?

**Comment by MI11435** [comment]
![Screenshot_ダンカグライク_20241014_211201.jpg](https://github.com/user-attachments/assets/8cfa75ac-23b5-48c0-a848-5815a74c4ad1)

These things happen.

**Comment by WickyPlays** [comment]
Okay, I get what you mean now.

However, the bug you mentioned was not clear enough, and that it happens when you increase text size, therefore the code will be using LowerLeft and LowerRight for the tasks.

Thanks for reporting the bug. (Released in 2.5.1a)
